# Generated by Django 3.2 on 2021-04-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dum_name', models.CharField(max_length=100)),
                ('dum_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
