# Generated by Django 3.2 on 2021-04-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dumDumbdum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dum',
            old_name='dum_description',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='dum',
            old_name='dum_name',
            new_name='subject',
        ),
    ]
